In [9]:
import numpy as np
batch_size = 10
p_randomgoal = 0.5
mask = np.random.rand(batch_size) <= p_randomgoal
print(mask)
print(mask.sum())

[False  True False  True  True False  True  True  True  True]
7


In [2]:
import torch

dataset = torch.load("/root/workspace/exorl/datasets/walker/rnd/replay.pt")

/tmp/ipykernel_1105914/1848340779.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  dataset = torch.load("/root/workspace/exorl/datasets/walker/rnd/replay.pt")


In [4]:
len(dataset._episodes_length)

5000

In [3]:
dataset._storage.keys()

dict_keys(['observation', 'action', 'reward', 'discount', 'physics'])

In [8]:
dataset._storage['reward'].shape

(5000, 1001, 1)

In [11]:
tt = dataset._storage['observation'].reshape(-1, 24)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [9]:
dataset._storage['action'].shape

(5000, 1001, 6)

In [17]:
dataset._storage['physics'].shape

(5000, 1001, 18)

In [3]:
import numpy as np

episode_ends = np.array([5, 11, 16, 33, 44])
episode_id = np.repeat(np.arange(len(episode_ends)), np.diff([0, *episode_ends]))
print(episode_id)

[0 0 0 0 0 1 1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 4 4 4 4
 4 4 4 4 4 4 4]


In [4]:
ep_len = [5, 6, 17, 11, 11]
episode_ends = np.cumsum(ep_len)
episode_ends

array([ 5, 11, 28, 39, 50])

In [4]:
import os
import shutil
log_path = "exp_local/offline"

for run_name in os.listdir(log_path):
    run_path = os.path.join(log_path, run_name)
    results_path = os.path.join(run_path, "eval_result")
    models_path = os.path.join(run_path, "models")
    models_list = os.listdir(models_path)
    models_list.sort(key=lambda x: int(x.split('.')[0]))
    for model_name in models_list[:-20]:
        model_path = os.path.join(models_path, model_name)
        print(f"Removing model: {model_path}")
        os.remove(model_path)
    results_list = os.listdir(results_path)
    results_list.sort(key=lambda x: int(x))
    for result_name in results_list[:-20]:
        result_path = os.path.join(results_path, result_name)
        print(f"Removing result: {result_path}")
        shutil.rmtree(result_path)



Removing result: exp_local/offline/20250915060743/eval_result/70000
Removing result: exp_local/offline/20250915060743/eval_result/80000
Removing result: exp_local/offline/20250915060743/eval_result/90000
Removing result: exp_local/offline/20250915060743/eval_result/100000
Removing result: exp_local/offline/20250915060743/eval_result/110000
Removing result: exp_local/offline/20250915060743/eval_result/120000
Removing result: exp_local/offline/20250915060743/eval_result/130000
Removing result: exp_local/offline/20250915060743/eval_result/140000
Removing result: exp_local/offline/20250915060743/eval_result/150000
Removing result: exp_local/offline/20250915060743/eval_result/160000
Removing result: exp_local/offline/20250915060743/eval_result/170000
Removing result: exp_local/offline/20250915060743/eval_result/180000
Removing result: exp_local/offline/20250915060743/eval_result/190000
Removing result: exp_local/offline/20250915060743/eval_result/200000
Removing result: exp_local/offline/20

In [1]:
import numpy as np

arr = np.ones(10)
arg_max = np.argmax(arr)

In [1]:
from url_benchmark.in_memory_hum_buffer import StepReplayBuffer, EpisodeBatch, ReplaySchema
import numpy as np

obs_horizon = 5
discount = 0.96
future = 0.98
p_randomgoal = 0.375
replay_buffer_max_step = 20
discount = 0.96
future = 0.98
p_randomgoal = 0.375

rep_schema = ReplaySchema(
    obs_key="proprio",
    action_key="action",
    reward_key="reward",
    obs_horizon=obs_horizon,
    cast_dtype=np.float32,
)
replay_buffer = StepReplayBuffer(
    capacity_steps=replay_buffer_max_step,
    schema=rep_schema,
    discount=discount,
    future=future,
    p_randomgoal=p_randomgoal,
)


In [2]:
replay_buffer = replay_buffer.load("/root/workspace/HILP/hilp_zsrl/exp_local/online/replay_buffer.pt")

/cpfs/user/caozhe/workspace/HILP/hilp_zsrl/url_benchmark/in_memory_hum_buffer.py:358: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(path, map_location="cp

In [3]:
replay_buffer._size

10240846

In [2]:
for i in range(7):
    episode_data = {"proprio": np.arange(0, 3), "action": np.random.randn(3, 2), "reward": np.random.randn(3)}
    replay_buffer.add_episode(episode_data, {})
replay_buffer._candidate_indices()

In [3]:
replay_buffer._storage['proprio']

array([                  0,                   1,                   2,
                         0,                   1,                   2,
                         0,                   1,                   2,
                         0,                   1,                   2,
                         0,                   1,                   2,
                         0,                   1,                   2,
              472446402665, 8243102913262518282])

In [4]:
episode_data = {"proprio": np.arange(99, 99+4), "action": np.random.randn(4, 2), "reward": np.random.randn(4)}
replay_buffer.add_episode(episode_data, {})
replay_buffer._candidate_indices()

In [5]:
replay_buffer.save("replay_buffer.pt")

In [6]:
new_buffer = StepReplayBuffer.load("replay_buffer.pt")

/cpfs/user/caozhe/workspace/HILP/hilp_zsrl/url_benchmark/in_memory_hum_buffer.py:358: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(path, map_location="cp

In [7]:
replay_buffer._valid

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False])

In [8]:
new_buffer._valid

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False])

In [1]:
import numpy as np
from url_benchmark.humanoid_utils import plot_tripanel_heatmaps_with_line, calc_z_vector_matrixes, compute_global_color_limits

test = np.random.randn(50, 10)
goal_z_cosine_sim_list, goal_distance_list, goal_absdist_list = calc_z_vector_matrixes(test)
plot_tripanel_heatmaps_with_line(goal_z_cosine_sim_list, goal_distance_list, goal_absdist_list, [f"latent_space_distance_g={goal_distance_list[g_idx].shape[-1]}.png" for g_idx in range(len(goal_distance_list))], "test")


In [7]:
import torch

pt_path = "/root/workspace/HILP/hilp_zsrl/exp_local/pr0.375_phi_exp0.5_phi_g0.96_False_mix0.5_False_256_collected_single_short_phih1024_state_sacTrue_hor5_rszFalse/20250909124712/models/1040000.pt"

payload = torch.load(pt_path)

/tmp/ipykernel_1032154/4184490847.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  payload = torch.load(pt_path)


RuntimeError: Attempting to deserialize object on CUDA device 2 but torch.cuda.device_count() is 2. Please use torch.load with map_location to map your storages to an existing device.

In [6]:
payload['agent'].feature_learner.state_dict()

OrderedDict([('running_mean',
              tensor([ 2.0147e-02,  6.0220e-01,  2.5520e-01,  2.2867e+00, -1.6187e-02,
                      -5.7289e-02, -8.5198e-01,  1.1617e-03, -5.2512e-01,  3.3111e-01,
                       1.3118e+00,  1.0967e+00,  6.3422e-02,  8.0338e-03, -1.2739e+00,
                       2.5497e+00,  1.9941e-02,  7.0307e-03,  1.9994e+00,  5.2392e-01,
                       3.3466e-02, -4.3577e-02,  7.6524e-03, -4.5467e-02,  1.0872e-01,
                       7.9773e-02, -2.2171e-02,  1.3644e-01,  1.2087e-02, -4.5943e+00,
                       8.9028e-01, -4.4692e-02,  3.7790e-02, -5.9837e-01, -1.9326e+00,
                       1.2736e+00,  5.4615e-02,  3.2852e-02,  7.9311e-01, -1.0502e-03,
                      -1.2139e-02,  6.6157e-01,  3.9624e-02, -1.7618e-02, -4.3989e-02,
                       4.6994e-01, -7.7827e-03, -3.9851e-02, -7.6388e-03, -1.5477e-01,
                      -2.5043e-01,  2.0338e+00,  7.3412e-01,  7.1308e-02,  1.5255e+00,
             

In [10]:
payload._episodes_length[0]


1000

In [3]:
import torch

ckpt_path = "/root/workspace/HILP/hilp_zsrl/exp_local/sf_h1int_0.98_f0.99_pr0.375_phi_exp0.5_phi_g0.96_qlFalse_False_mix0.5_False_512_collected_single_short_phih2048_state/20250908103821/models/520000.pt"
with open(ckpt_path, 'rb') as f:
    payload = torch.load(f)

print(payload.keys())
print(payload['agent'])

dict_keys(['agent', 'global_step', 'global_episode'])


/tmp/ipykernel_455176/4288144180.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  payload = torch.load(f)


In [ ]:
payload['agent'].feature_learner.state_dict()

OrderedDict([('running_mean',
              tensor([ 4.9263e-02, -3.3308e-01,  4.6538e-02, -8.5039e-03, -2.3981e-02,
                      -9.2834e-02, -3.2790e-03,  4.1932e-02, -5.2947e-02,  3.7770e-01,
                       1.0527e+00,  3.1044e+00, -1.1646e-02,  4.1144e-02, -2.0607e-02,
                       7.7021e+00,  1.2694e-01,  2.0665e+00,  2.3742e-02,  2.4466e+00,
                      -1.8919e-02, -8.3937e-02,  6.5327e-03,  1.0447e-01, -3.5178e-02,
                       9.8109e-02,  3.9984e+00, -1.0578e-01, -1.3239e+00,  3.0720e-02,
                       1.0095e-02,  8.4214e-02,  1.4523e-02, -4.3836e-02,  5.5517e-02,
                      -4.6555e-02, -4.0819e-02,  7.9044e-03, -4.1037e-02, -2.9813e-02,
                       9.1508e-01,  3.3952e-02, -6.9857e-02, -1.2653e+00, -1.4300e+00,
                       1.2560e+00,  1.9915e+00,  2.4585e-02, -5.1354e-01,  7.7444e-02,
                       1.0205e+00,  9.8395e-04,  4.5235e-02,  1.6474e-03, -4.0606e-04,
             

: 

In [ ]:
from url_benchmark.dataset_utils.hilbert_dataset import HilbertRepresentationDataset

dataset = HilbertRepresentationDataset(data_dir="/root/workspace/HugWBC/dataset/Mixture/model_0",
                                       use_history_action=False,
                                       discount=0.96,
                                       obs_horizon=5,
                                       full_loading=False,
                                       goal_future=0.98,
                                       p_randomgoal=0.375)

# print(dataset[0])

/root/miniconda3/envs/hilp_zsrl/lib/python3.8/site-packages/glfw/__init__.py:917: GLFWError: (65550) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)


Sampling method, p_randomgoal: 0.375, future: 0.98, discount: 0.96 horizon: 5 use_history_action: False


  0%|          | 0/1 [00:00<?, ?it/s]

/
 ├── data
 │   ├── actions (11522042, 19) float32
 │   ├── clock (11522042, 2) float32
 │   ├── commands (11522042, 11) float32
 │   ├── dones (11522042,) bool
 │   ├── privileged (11522042, 24) float32
 │   ├── proprio (11522042, 44) float32
 │   ├── rewards (11522042,) float32
 │   └── terrain (11522042, 221) float32
 └── meta
     ├── ep_start_obs (200000, 4, 76) float32
     ├── episode_command_A (200000, 11) float32
     ├── episode_command_B (200000, 11) float32
     ├── episode_ends (200000,) int64
     ├── episode_reward (200000,) float32
     └── episode_step_reward (200000,) float32


100%|██████████| 1/1 [00:03<00:00,  3.04s/it]


In [3]:
for k, v in dataset[0].items():
    print(k, v.shape)

obs torch.Size([220])
next_obs torch.Size([220])
future_obs torch.Size([220])
discount torch.Size([])
